spring.application.name=activity-service
server.port=8082

# MongoDB
spring.mongodb.uri=mongodb://localhost:27017/fitness_activity
spring.mongodb.database=fitness_activity

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.queue.name=activity.queue
rabbitmq.exchange.name=activity.exchange
rabbitmq.routing.key=activity.created
