server.port=8083

spring.mongodb.uri=mongodb://localhost:27017/fitness_recommendation
spring.mongodb.database=fitness_recommendation

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.queue.name=activity.queue
rabbitmq.exchange.name=activity.exchange
rabbitmq.routing.key=activity.created

# Gemini
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=${GEMINI_API_URL}

eureka.instance.prefer-ip-address=true